application:
  name: DevOpsSimulator
  version: 1.0.0
  environment: production
  
server:
  host: 0.0.0.0
  port: 8080
  ssl_enabled: true
  
logging:
  level: INFO
  format: json
  
# Development configuration (enabled via environment variable)
development:
  enabled: false
  port: 3000
  hot_reload: false
  debug_mode: false
  mock_apis: false

# Application Configurations

server:
  port: 8080  # Port to run the server on

database:
  host: localhost  # Database host address
  port: 5432       # Database port
  user: admin      # Database username
  password: secret # Database password
